baseURL = 'https://www.nickcouryruns.com/'
languageCode = 'en-us'
title = 'Nick Coury Runs'
theme = 'ncr'

[params]
  description = 'Ultrarunning, negative splitting, and pacing strategy'
  author = 'Nick Coury'
  profileImage = 'images/profile.jpg'

[permalinks]
  posts = '/posts/:slug/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML', 'RSS']
